name: build engine for pi4

on:
  push:
    tags:
      - '**'
  pull_request:
    branches: [ ci ]
  repository_dispatch:
  workflow_dispatch:
  workflow_call:
  
jobs:
  populate-engine-src-cache:
    name: 'Prepopulate engine source cache'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - run: |
          echo github.ref: ${{ github.ref }}

      - name: Read stable engine version
        id: engine-version-stable

        # Read the engine.version.stable file and trim away anything that's not a hex digit
        # (So we don't include whitespace in the output variable, if that's possible)
        run: echo ::set-output name=hash::$(cat engine.version.stable | tr -dc [:xdigit:])
      
      - name: Log stable engine version
        run: |
          echo stable engine version: "${{ steps.engine-version-stable.outputs.hash }}"
      
      - name: Create engine cache stamp dir
        shell: bash
        run: |
          mkdir -p engine-cache-stamp

      - uses: actions/cache@v3
        id: stamp-cache
        with:
          path: engine-cache-stamp
          key: engine-cache-stamp-${{ steps.engine-version-stable.outputs.hash }}

      - name: Log cache hit
        shell: bash
        run: |
          echo cache hit? ${{ steps.stamp-cache.outputs.cache-hit }}

      - uses: actions/cache@v3
        id: cache
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        with:
          path: engine
          key: engine-${{ steps.engine-version-stable.outputs.hash }}

      - name: Setup environment variables
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          # echo DEPOT_TOOLS_UPDATE=0 >> $GITHUB_ENV
          echo GCLIENT_PY3=1 >> $GITHUB_ENV
          echo $PATH
          
      - name: Clone depot tools
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git $GITHUB_WORKSPACE/depot_tools
          echo $GITHUB_WORKSPACE/depot_tools >> $GITHUB_PATH
      
      - name: Setup environment variables
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          # echo DEPOT_TOOLS_UPDATE=0 >> $GITHUB_ENV
          echo GCLIENT_PY3=1 >> $GITHUB_ENV
          echo $PATH
          echo is-host: ${{ inputs.is-host }}
          
      - name: Setup gclient
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          gclient --version
          echo DEPOT_TOOLS_UPDATE=0 >> $GITHUB_ENV
          
      - name: Bootstrap engine environment
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' && !startsWith(github.ref, 'refs/tags/3.3') }}
        shell: bash
        run: |
          mkdir -p engine
          echo 'solutions = [{ "managed": False, "name": "src/flutter", "url": "https://github.com/flutter/engine.git", "deps_file": "DEPS", "custom_vars":{ "download_linux_deps": True, "download_android_deps": False}, },]' > engine/.gclient
      
      - name: Bootstrap engine environment (with libcxx workaround)
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' && startsWith(github.ref, 'refs/tags/3.3') }}
        shell: bash
        run: |
          mkdir -p engine
          echo 'solutions = [{ "managed": False, "name": "src/flutter", "url": "https://github.com/flutter/engine.git", "deps_file": "DEPS", "custom_vars":{ "download_linux_deps": True, "download_android_deps": False}, "custom_deps": {"src/third_party/libcxx": "https://llvm.googlesource.com//llvm-project/libcxx@54c3dc7343f40254bdb069699202e6d65eda66a2"}, }, }]' > engine/.gclient
      
      - name: Install engine sources
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        shell: bash
        working-directory: engine
        run: |
          gclient sync --revision src/flutter@${{ steps.engine-version-stable.outputs.hash }} -R -D
      
      - name: Install linux arm sysroot
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        shell: bash
        working-directory: engine
        run: |
          ./src/build/linux/sysroot_scripts/install-sysroot.py --arch=arm

      - name: Prune git history
        if: ${{ steps.stamp-cache.outputs.cache-hit != 'true' }}
        shell: bash
        working-directory: engine
        run: |
          for FILE in $(find . -type d -name .git)
          do
            pushd "$FILE/.."
            git rev-parse HEAD > .git/shallow
            git tag -d $(git tag -l) || true
            for ref in $(git for-each-ref --format="%(refname)")
            do
              git update-ref -d "$ref"
            done
            git remote remove origin
            git reflog expire --expire=all --all
            git gc --prune=all
            popd
          done
          
  build-engine:
    name: 'build engine'
    runs-on: ubuntu-latest
    needs: populate-engine-src-cache
    strategy:
      matrix:
        artifact-name:
          - pi4
          - pi4-64
          - armv7-generic
          - aarch64-generic
        runtime-mode:
          - debug
          - profile
          - release
        include:
          - artifact-name: pi4
            cpu: arm
            arm-tune: cortex-a72
          - artifact-name: pi4-64
            cpu: arm64
            arm-tune: cortex-a72
          - artifact-name: armv7-generic
            cpu: arm
            arm-tune: generic
          - artifact-name: aarch64-generic
            cpu: arm64
            arm-tune: generic
          - runtime-mode: debug
            has-gen-snapshot: false
          - runtime-mode: profile
            has-gen-snapshot: true
          - runtime-mode: release
            has-gen-snapshot: true
    steps:
      - uses: actions/checkout@v1
      
      - name: Read stable engine version
        id: engine-version-stable
        run: echo ::set-output name=hash::$(cat engine.version.stable)
        
      - name: Test output
        run: echo ${{ steps.engine-version-stable.outputs.hash }}
      
      - name: build engine
        uses: ./.github/actions/build-engine
        with:
          ref: "${{ steps.engine-version-stable.outputs.hash  }}"
          is-host: false
          runtime-mode: ${{ matrix.runtime-mode }}
          os: linux
          cpu: ${{ matrix.cpu }}
          additional-gn-args: '--embedder-for-target --disable-desktop-embeddings --no-build-glfw-shell --no-build-embedder-examples --no-goma'
          additional-raw-gn-args: 'arm_tune = "${{ matrix.arm-tune }}"'
           
      - name: upload artifacts (with gen_snapshot)
        if: ${{ matrix.has-gen-snapshot != 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-${{ matrix.artifact-name }}-${{ matrix.runtime-mode }}
          path: |
            ${{ github.workspace }}/engine/src/out/build/compile_commands.json
            ${{ github.workspace }}/engine/src/out/build/libflutter_engine.so
            ${{ github.workspace }}/engine/src/out/build/icudtl.dat
            ${{ github.workspace }}/engine/src/out/build/flutter_embedder.h
            ${{ github.workspace }}/engine/src/out/build/clang_x64/gen_snapshot
      
      - name: upload artifacts (without gen_snapshot)
        if: ${{ matrix.has-gen-snapshot != 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-${{ matrix.artifact-name }}-${{ matrix.runtime-mode }}
          path: |
            ${{ github.workspace }}/engine/src/out/build/compile_commands.json
            ${{ github.workspace }}/engine/src/out/build/libflutter_engine.so
            ${{ github.workspace }}/engine/src/out/build/icudtl.dat
            ${{ github.workspace }}/engine/src/out/build/flutter_embedder.h


  release:
    name: 'Publish release'
    runs-on: ubuntu-latest
    needs: [build-engine]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Read stable engine version
        id: engine-version-stable
        run: echo ::set-output name=hash::$(cat engine.version.stable)
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-pi4-debug
          path: pi4-debug
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-pi4-profile
          path: pi4-profile
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-pi4-release
          path: pi4-release
          
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-pi4-64-debug
          path: pi4-64-debug
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-pi4-64-profile
          path: pi4-64-profile
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-pi4-64-release
          path: pi4-64-release
          
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-armv7-generic-debug
          path: armv7-generic-debug
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-armv7-generic-profile
          path: armv7-generic-profile
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-armv7-generic-release
          path: armv7-generic-release
      
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-aarch64-generic-debug
          path: aarch64-generic-debug
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-aarch64-generic-profile
          path: aarch64-generic-profile
        
      - uses: actions/download-artifact@v3
        with:
          name: ${{ steps.engine-version-stable.outputs.hash }}-aarch64-generic-release
          path: aarch64-generic-release
          
      - name: Package Pi4 artifacts
        run: |
          mkdir -p pi4
          cd pi4
          cp ../engine.version.stable ./engine.version
          cp ../pi4-debug/libflutter_engine.so ./libflutter_engine.so.debug
          cp ../pi4-profile/libflutter_engine.so ./libflutter_engine.so.profile
          cp ../pi4-release/libflutter_engine.so ./libflutter_engine.so.release
          cp ../pi4-debug/flutter_embedder.h ./flutter_embedder.h
          cp ../pi4-debug/icudtl.dat ./icudtl.dat
          cp ../pi4-profile/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_profile
          cp ../pi4-release/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_release
          XZ_DEFAULTS="-T 0" tar -cJvf ../pi4.tar.xz *
      
      - name: Package Pi4-64 artifacts
        run: |
          mkdir -p pi4-64
          cd pi4-64
          cp ../engine.version.stable ./engine.version
          cp ../pi4-64-debug/libflutter_engine.so ./libflutter_engine.so.debug
          cp ../pi4-64-profile/libflutter_engine.so ./libflutter_engine.so.profile
          cp ../pi4-64-release/libflutter_engine.so ./libflutter_engine.so.release
          cp ../pi4-64-debug/flutter_embedder.h ./flutter_embedder.h
          cp ../pi4-64-debug/icudtl.dat ./icudtl.dat
          cp ../pi4-64-profile/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_profile
          cp ../pi4-64-release/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_release
          XZ_DEFAULTS="-T 0" tar -cJvf ../pi4-64.tar.xz *
      
      - name: Package generic ARMv7 artifacts
        run: |
          mkdir -p armv7-generic
          cd armv7-generic
          cp ../engine.version.stable ./engine.version
          cp ../armv7-generic-debug/libflutter_engine.so ./libflutter_engine.so.debug
          cp ../armv7-generic-profile/libflutter_engine.so ./libflutter_engine.so.profile
          cp ../armv7-generic-release/libflutter_engine.so ./libflutter_engine.so.release
          cp ../armv7-generic-debug/flutter_embedder.h ./flutter_embedder.h
          cp ../armv7-generic-debug/icudtl.dat ./icudtl.dat
          cp ../armv7-generic-profile/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_profile
          cp ../armv7-generic-release/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_release
          XZ_DEFAULTS="-T 0" tar -cJvf ../armv7-generic.tar.xz *
      
      - name: Package generic AArch64 artifacts
        run: |
          mkdir -p armv8-generic
          cd armv8-generic
          cp ../engine.version.stable ./engine.version
          cp ../aarch64-generic-debug/libflutter_engine.so ./libflutter_engine.so.debug
          cp ../aarch64-generic-profile/libflutter_engine.so ./libflutter_engine.so.profile
          cp ../aarch64-generic-release/libflutter_engine.so ./libflutter_engine.so.release
          cp ../aarch64-generic-debug/flutter_embedder.h ./flutter_embedder.h
          cp ../aarch64-generic-debug/icudtl.dat ./icudtl.dat
          cp ../aarch64-generic-profile/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_profile
          cp ../aarch64-generic-release/clang_x64/gen_snapshot ./gen_snapshot_linux_x64_release
          XZ_DEFAULTS="-T 0" tar -cJvf ../aarch64-generic.tar.xz *
      
      - uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            pi4.tar.xz
            pi4-64.tar.xz
            armv7-generic.tar.xz
            aarch64-generic.tar.xz
  
    
